category: day1
points:   10
short:    binary
name:     "Язык хакеров"
author:   nsychev
description: >
    Привет! Мы тебя уже давно ждем!
    
    Сейчас мы раскрываем одну группировку **хакеров** из Америки. Говорят, что 
    они говорят крупномасштабную атаку. Однако, мы уверены, что они в этом не
    шарят. Тебе предстоит помочь нам ракрыть их тайные планы.
    
    В каждой миссии мы ждем от тебя **флаг** — секретную информацию, которую 
    прячут хакеры. Удачи!
    
    Переписка хакеров по электронной почте выглядит очень странно... О чём это
    они говорят?
attachments:
  - email.txt
flags:
  - text: first_flag_is_the_easiest_flag

