category: day7
points:   25
short:    word7
name:     "Word: Corrupt"
author:   "nsychev, inspired by vos@spbctf"
description: >
    Объявляю сегодняшний день **международным днём Ворда**! Говорят, что этот файл напичкан флагами чуть более, чем полностью.
    
    *В этот таск сдай флаг 7*
url: https://yadi.sk/i/j8HBMVbX3Y4tz7
flags:
  - text: "flag7_easy_binary_task"
