category: day4
points:   15
short:    bad-or
name:     "Плохой OR"
author:   nsychev
description: >
    Иногда логические операции тоже используют в криптографии.
    
    Возьмем два бита *a* и *b*. Операцией **or** («или») назовем такую операцию над битами, результат которой равен 1, если хотя бы один из битов равен 1.
    Например, если *a* = 1, *b* = 0, то (*a* **or** *b*) = 1. А если *a* = 0 и *b* = 0, то (*a* **or** *b*) = 0. Наверняка ты в школе встречался с такой операцией :)
    
    Акакию не нравится такое **или** и он сделал своё — плохое. Плохое **или** работает так же, как и обычное, но при *a* = *b* = 1 возвращает 0. Для натуральных чисел он делает
    «плохое **или**» так: пишет числа в двоичной системе счисления и над соответствующими парами бит выполняет «плохое **или**».
    
    Теперь Акакий хочет шифровать. Он берет число *x*, которое хочет зашифровать, и число-ключ *k*, считает между ними «плохое **или**» и записывает получившееся число *c* — 
    это и есть зашифрованный *x*.
    
    Однако, Акакий упорно отказывается рассказывать нам алгоритм расшифровки.
    
    Может быть, ты сможешь расшифровать его послание?
    
    Известно, что он пользовался ключом `84` и зашифрованные числа были такими: `45 49 53 60 11 54 53 48 11 59 38 11 61 39 11 44 59 38`. 
    Потом нужно перевести каждое число в символ с таким ASCII-кодом и сдать как флаг.
flags:
  - text: "yeah_bad_or_is_xor"
