category: day4
points:   15
short:    nyan
name:     "Музыка из игры"
author:   evgfilim1
description: >
    Когда-то, в начале 2010-х, была популярна одна очень интересная игра для 
    смартфонов. У меня осталась лишь музыка из этой игры, которая длится 
    **десять часов**. Времени на её полное прослушивание у меня нет, да и у 
    тебя тоже, но я дам тебе послушать отрывок. Возможно, ты сможешь найти в 
    нём *что-то интересное*.
url: "https://yadi.sk/d/czXmcwlP3XpXZb"
flags:
  - text: i_love_ten_hours_music

