category: day10
points:   35
short:    xaxxor
name:     "Приключения Петра"
author:   nsychev
description: >
    Вы слышали удивительную историю Петра Пывнера? 
    Это один из самых известных российских хакеров! Не верите?

    Лучше поверьте — на его счету взлом Пентагона, американских выборов и других
    антироссийских мест.
    
    Он создал свой сайт в интернете и ставит 35 баллов на то, что никто не найдет флаг.
    Чтобы защитить свой флаг по-настоящему, он просто никому не говорит адрес сайта.
    
    Но мы уверены, что вам и это не помешает — покажите, кто тут настоящий хакер!
flags:
  - text: "easy_flag_for_hard_osint_master"

