category: day3
points:   15
short:    decode
name:     "Trash"
author:   nsychev, idea by vos@spbctf
description: >
    Какой-то треш!
    
    ┬юЄ эр° Їыру: яш°ш ЄЁрэёышЄюь "ъюфшЁютъш эр°х тёх", Ёрчфхы щ ёыютр эшцэшь яюфўхЁъштрэшхь
flags:
  - text: "kodirovki_nashe_vse"
