category: day10
points:   15
short:    stupidphoto
name:     "Плохой фотограф"
author:   netosha
description: >
 Antiфотограф Антоша любит фотографировать абстрактные картинки и отсылать это синеволосому другу.


 Друг такого долго терпеть не мог, поэтому сделал обидные стикеры для Тоши. [Стикеры](https://t.me/addstickers/solveme_task)
url: "https://imgur.com/a/Q93anz6"
flags:
  - text: "LEBEDEV_KROTOOY"
