category: day7
points:   15
short:    word4
name:     "Word: Figure"
author:   "nsychev, inspired by vos@spbctf"
description: >
    Объявляю сегодняшний день **международным днём Ворда**! Говорят, что этот файл напичкан флагами чуть более, чем полностью.
    
    *В этот таск сдай флаг 4*
url: https://yadi.sk/i/j8HBMVbX3Y4tz7
flags:
  - text: "flag4_first_stegano_easy"
