category: day9
points:   10
short:    wait
name:     "Просто подожди"
author:   evgfilim1
description: >
    Ты, наверное, устал решать эти таски? А ещё учиться надо, на мероприятия
    ходить, с друзьями играть и общаться, спать, в конце концов! Поэтому, я 
    сделал для тебя очень лёгкий таск. Чтобы получить флаг, нужно лишь
    подождать немного. Всё просто, не правда ли?

    Напомню, что ждать ты можешь не только с компьютера в лицее ;)
url: "https://day9.upml.tech/"
flags:
  - text: just_waiting_for_a_miracle

