category: day8
points:   15
short:    news
name:     "Новости"
author:   nsychev
description: >
    Каждый день по телевизору говорят какую-то дичь!
    
    Это настолько странно, что я даже записал передачу на диктофон…
    
    *Подсказка*: вряд ли ты найдешь в словах на записи какой-то смысл. Что могло быть зашифровано в этих словах?
attachments:
  - fragment.wav
flags:
  - text: voice_recognition

