category: day5
points:   20
short:    morersa
name:     "Больше RSA"
author:   nsychev
description: >
    Эх, как же жалко. Я думал, Light RSA надежен, а ты взял и взломал :(
    
    Ладно, теперь буду шифровать тексты только настоящим RSA! Зато это настолько
    надежно, что можно вешать пароли на стенку. Или даже в условие таска…
    
    ```
    n = 260559312989568206199788383015888592137
    e = 65537
    encrypted_flag = 61062251709536152777829542272261552848
    ```
    
    Расшифрованное число в шестнадцатеричной системе будет равно `hex(flag)`.
flags:
  - text: "too_small_rsa"
