category:   day1
points:     25
short:      hash
name:       "Пароли"
author:     nsychev
description: >
    Нашли пароль от базы данных, но он захеширован. Не поможешь его взломать и получить пароль? 
    Говорят, что эти «хакеры» часто используют популярные пароли. 
    
    Сам хеш: `28b5828ac3b16e22c26077eedf5674ff`
    
    *Подсказка*: не знаешь что-нибудь? Попробуй погуглить
flags:
 - text: hashhash