category: day9
points:   30
short:    strong
name:     "Strong Crypto"
author:   nsychev
description: >
    Не верите в меня? И зря!
    
    Мой **принципиально новый** алгоритм защиты информации защитит всё как настоящая броня!
    
    Хоть на первый взгляд он состоит из простых кирпичиков, их неповторимая комбинация не позволит злостным хакерам достать ни одного бита содержащейся внутри информации!
    
    Поэтому я абсолютно уверен, что на этот раз этот таск останется нерешаемым!
    
    И да, вот секретик: `vfquoCkcitizDacwfnoloDfxdwixcsfbi`
attachments:
  - script.py
flags:
  - text: DearFriendDontBecomeACryptologist
