category: day6
points:   10
short:    autologin
name:     "Автоматический вход"
author:   evgfilim1
description: >
    Пользователи попросили разработчиков этого сайта сделать автоматический
    вход в систему. Казалось бы, что тут такого? Но вам, как русским хакерам,
    нужно найти *очень секретную информацию* на этом сайте и сообщить её нам.
url: "https://day6.upml.tech/"
flags:
  - text: so_insecure

