category:   day5
points:     10
short:      html
name:       "Summer ICO"
author:     nsychev
description: >
    Блокчейн-ассоциация МБОУ СОШ №53 начала глобальную экспансию — новый проект
    Summer ICO уже известен по всему миру, а через два месяца ожидается, что 
    капитализация данной кампании составит миллиард долларов!
    
    Правда, нам кажется, что их HTML-разработчик недостаточно квалифицирован, и 
    хранит пароли не очень безопасно.
    
    Но где?
url:        https://day5.upml.tech/
flags:
 - text: "mum_i_am_hacker"