category: day2
points:   15
short:    encodings
name:     "Кодировочки"
author:   nsychev
description: >
    У вас новое сообщение!
    
    `NjY2YzYxNjc1ZjY5NzM1ZjYzNmM2ZjczNjU3MjVmNzQ2ODYxNmU1Zjc5NmY3NTVmNjU3ODcwNjU2Mzc0`
flags:
  - text: "flag_is_closer_than_you_expect"
