category: day4
points:   25
short:    proverbs
name:     "Пословицы и поговорки"
author:   grinnds
description: >
  Русские пословицы и поговорки являются достоянием всего народа. 
  Они складывались исторически и обобщили народную мудрость.

  Мы порой даже можем не замечать,
  сколько таких устойчивых фраз знаем и используем в повседневной речи.
  Ведь они позволяют отлично проиллюстрировать и подчеркнуть 
  практически любую мысль!

  Поэтому я решил составить для вас сборник пословиц и поговорок,
  чтобы вы не забывали их и чаще пользовались ими в своей речи.
  
  *Подсказка*: попробуйте воспользоваться ранее встречавшимися кодировками
attachments:
  - proverbial_collection.txt
flags:
  - text: "ascii_i5_so_c00l"
