category: day5
points:   15
short:    gif
name:     "Самая быстрая гифка"
author:   grinnds
description:
Однажды, пролистывая свои фотографии, я заметил нечто странное.
Это была красочна гифка с быстро мелькающими цветными символами.
 
Я был удивлён, так как не помнил, чтобы эта гифка
когда-либо была у меня на компьютере.

К сожалению, картинки слишком быстро меняются, поэтому я ничего не смог
разглядеть. Помогите мне решить задание и разгадать шифр.

Какие же тайны скрываются в ней?
Может, там рецепт тортика?
attachments:
  - GIF.gif
flags:
  - text: "do_not_blink_or_you_will_miss_me"