category: day4
points:   15
short:    GIF
name:     "Самая быстрая гифка"
author:   grinnds
description:
  Однажды, пролистывая свои фотографии, на мои глаза попалась красочная гифка.
  Но, к сожалению, картинки слишком быстро меняются, и я ничего не разглядев,
  решил попросить вашей помощи.
  
  Какие же тайны скрываются в ней?
  Может там рецепт тортика?
attachments:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
  - 6.png
  - 7.png
  - 8.png
  - 9.png
  - GIF.gif
flags:
  - text: "do_not_blink_or_you_will_miss_me"