category: day1
points:   5
short:    agents
name:     "Начни отсюда"
author:   nsychev
description: >
    Привет! Мы тебя уже давно ждем!
    
    Хочешь стать **хакером**? Тогда тебе предстоит увлекательный путь.
    
    Помоги нам раскрыть одну группировку **хакеров** из Америки. Говорят, что 
    они готовят крупномасштабную атаку. Однако, мы уверены, что они в этом не
    шарят. Необходимо узнать их тайные планы!
    
    Мы подготовили несколько миссий: ты их видишь на главной странице. В каждой 
    миссии мы ждем от тебя **флаг** — секретную информацию, которую нужно достать. 
    За каждый флаг ты получишь некоторое количество баллов (чем сложнее миссия, тем
    больше баллов). Выиграй всех и получи **приз**!
    
    Если что-то не получается — попробуй поискать в интернете.
    
    Чтобы получить свои первые 5 баллов, сдай в этом задании флаг `get_5_points`
flags:
  - text: get_5_points

