category: day8
points:   20
short:    run
name:     "SSH"
author:   nsychev
description: >
    Мы нашли уязвимый сервер: кажется, на порту 2018 на сервере `secret.upml.tech` поднято что-то непонятное! Логин `run`, пароль `run`
    
    Узнайте, как туда подключиться и получить флаг
    
    *Подсказка*: по данному адресу и порту поднят SSH-сервер. Просто переходить по ссылке бессмысленно. Узнай, как подключаться к SSH-серверу.
flags:
  - text: bash_is_so_easy
