category: day9
points:   10
short:    book
name:     "Писатель"
author:   nsychev
description: >
    Решил написать книгу чтобы стать таким же крутым, как Брюс Шнейер.
    
    Хочу, чтобы у каждого ребенка она была в домашней библиотеке.
    
    Планирую первый тираж выпустить в 2020, но уже сейчас сделал титульную
    страницу. Как вам?
url: https://yadi.sk/i/C20qoHaI3Y92nM
flags:
  - text: itseasyevenforme